name: Vector Database ICP integration Test

on: 
  push:
    branches:
      - main
      - compwise
  pull_request:
    types: [labeled,synchronize,reopened]

jobs:
  vector-database-integration-test:
    runs-on:
      labels: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: aviate-labs/setup-dfx@v0.2.6
      with:
        dfx-version: 0.14.2
    - run: |
        dfx start --background
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: |
        rustup target add wasm32-unknown-unknown
    - run: |
        dfx generate

        dfx identity import owner --seed-file keys/owner.seed
        dfx identity use owner
        dfx canister create vector_database_backend
        dfx deploy vector_database_backend

        npm install 
        npm test
        dfx stop

